name: ffmpeg-arm64

on:
  workflow_dispatch:
    # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest-arm
    env:
      TIMESTAMP: ${{ github.run_id }}_${{ github.run_number }}
      ARCH: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set file permissions
        run: |
          chmod +x configs/ffmpeg-for-lambda/build.sh
          chmod +x configs/ffmpeg-for-lambda/arm64/build.sh

      - name: Build FFmpeg for ARM64
        run: |
          cd configs/ffmpeg-for-lambda/
          ./build.sh --arm64-only --timestamp ${TIMESTAMP}

      - name: List artifact directories
        run: |
          echo "Checking for build artifacts..."
          echo "Working directory: $(pwd)"
          ls -la configs/ffmpeg-for-lambda/build/ || echo "configs/ffmpeg-for-lambda/build/ directory not found"
          ls -la configs/ffmpeg-for-lambda/build/archive/ || echo "configs/ffmpeg-for-lambda/build/archive/ directory not found"
          ls -la configs/ffmpeg-for-lambda/build/archive/$TIMESTAMP/ || echo "configs/ffmpeg-for-lambda/build/archive/$TIMESTAMP/ directory not found"
          find configs/ffmpeg-for-lambda/ -name "*.zip" -type f

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-arm64-build
          path: configs/ffmpeg-for-lambda/build/archive/${{ env.TIMESTAMP }}
          retention-days: 7
          if-no-files-found: warn
