name: ffmpeg-all

on:
  workflow_dispatch:
    # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: ${{ github.run_id }}_${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set file permissions
        run: |
          chmod +x configs/ffmpeg-for-lambda/build.sh
          chmod +x configs/ffmpeg-for-lambda/amd64/build.sh
          chmod +x configs/ffmpeg-for-lambda/arm64/build.sh

      - name: Build FFmpeg for all architectures
        run: |
          ./build.sh --timestamp ${TIMESTAMP}

      - name: Create build summary
        run: |
          echo "Creating build summary..."
          cat > "build/${TIMESTAMP}/summary.txt" << EOF
          FFmpeg Build Summary
          ===================
          Build ID: ${TIMESTAMP}
          Date: $(date)

          This build includes:
          - AMD64 binaries for Amazon Lambda
          - ARM64 binaries for Amazon Lambda

          Archives:
          - build/archive/${TIMESTAMP}/ffmpeg-amd64_${TIMESTAMP}.zip
          - build/archive/${TIMESTAMP}/ffmpeg-arm64_${TIMESTAMP}.zip
          - build/archive/${TIMESTAMP}/ffmpeg-combined_${TIMESTAMP}.zip

          EOF

          # Copy the summary to the archive directory
          cp "build/${TIMESTAMP}/summary.txt" "build/archive/${TIMESTAMP}/"

          # Create a latest.txt file with the current build timestamp
          echo "${TIMESTAMP}" > "build/latest.txt"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-combined-build
          path: build/archive/${TIMESTAMP}
          retention-days: 7
